"""Assemble the results table and render the reproducible results.md.

results.md is a generated artifact (committed as the study's evidence), not prose to
be hand-edited. The narrative lives in the top-level README.
"""

from __future__ import annotations

from datetime import date
from functools import partial
from pathlib import Path

import numpy as np
import pandas as pd

from ..config import StudyConfig
from ..models.registry import BENCHMARK_NAMES, default_models
from ..study import StudyResults
from .stats import (
    block_bootstrap_ci,
    deflated_sharpe_ratio,
    max_drawdown,
    probabilistic_sharpe_ratio,
    sharpe_ratio,
)

_MODEL_ORDER = list(default_models())


def _per_period_sharpe(net: pd.Series) -> float:
    r = net.to_numpy(dtype=float)
    sd = r.std(ddof=1) if r.size > 1 else 0.0
    return float(r.mean() / sd) if sd > 0 else 0.0


def results_table(study: StudyResults) -> pd.DataFrame:
    """One tidy row per (asset, horizon, model) with metrics, stats, and PnL."""
    group_sr: dict[tuple[str, int], list[float]] = {}
    for run in study.runs:
        group_sr.setdefault((run.asset, run.horizon), []).append(
            _per_period_sharpe(run.strategy.net)
        )

    rows: list[dict[str, object]] = []
    for run in study.runs:
        net = run.strategy.net
        ppy = run.strategy.periods_per_year
        lo, hi = block_bootstrap_ci(net, partial(sharpe_ratio, periods_per_year=ppy), n_boot=500)
        srs = group_sr[(run.asset, run.horizon)]
        trials_sr_std = float(np.std(srs, ddof=1)) if len(srs) > 1 else 0.0
        rows.append(
            {
                "asset": run.asset,
                "horizon": run.horizon,
                "model": run.model,
                "rmse": run.metrics["rmse"],
                "r2_oos": run.metrics["r2_oos"],
                "dir_acc": run.metrics["dir_acc"],
                "rank_ic": run.metrics["rank_ic"],
                "dm_stat": run.dm_stat_vs_rw,
                "dm_p_vs_rw": run.dm_p_vs_rw,
                "pt_stat": run.pt_stat,
                "pt_p": run.pt_p,
                "sharpe_net": sharpe_ratio(net, ppy),
                "sharpe_lo": lo,
                "sharpe_hi": hi,
                "max_dd": max_drawdown(run.strategy.equity),
                "psr": probabilistic_sharpe_ratio(net),
                "dsr": deflated_sharpe_ratio(net, len(srs), trials_sr_std),
                "trades": int((run.strategy.turnover > 0).sum()),
            }
        )

    table = pd.DataFrame(rows)
    order = {name: i for i, name in enumerate(_MODEL_ORDER)}
    table["_o"] = table["model"].map(order)
    return table.sort_values(["asset", "horizon", "_o"]).drop(columns="_o").reset_index(drop=True)


def _fmt(value: float, spec: str = ".3f") -> str:
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return "—"
    return format(value, spec)


def _md_table(rows: list[list[str]], header: list[str]) -> str:
    lines = ["| " + " | ".join(header) + " |", "| " + " | ".join(["---"] * len(header)) + " |"]
    lines += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(lines)


def _headline(table: pd.DataFrame) -> str:
    ml = table[~table["model"].isin(BENCHMARK_NAMES)]
    # "Beat" requires a *lower* loss (dm_stat < 0), not merely a significant difference.
    beats_rw = ml[(ml["dm_stat"] < 0) & (ml["dm_p_vs_rw"] < 0.05)]
    timing = ml[(ml["pt_stat"] > 0) & (ml["pt_p"] < 0.05)]
    ci_pos = ml[ml["sharpe_lo"] > 0]
    best = table.loc[table["dsr"].idxmax()]
    return (
        f"- Of **{len(ml)}** ML (model x asset x horizon) settings, "
        f"**{len(beats_rw)}** beat the random walk on squared error at p<0.05 "
        f"(Diebold-Mariano), and **{len(timing)}** showed significant sign-timing "
        f"skill at p<0.05 (Pesaran-Timmermann).\n"
        f"- After costs, **{len(ci_pos)}** ML strategies had a net Sharpe whose 95% "
        f"bootstrap CI excluded zero.\n"
        f"- Best deflated Sharpe (guarding against the {table.groupby(['asset','horizon']).ngroups}"
        f"-way model search): **{_fmt(best['dsr'], '.2f')}** "
        f"({best['model']}, {best['asset']}, h={int(best['horizon'])})."
    )


def write_markdown(
    config: StudyConfig, table: pd.DataFrame, figures: list[str], path: Path
) -> None:
    cfg = config
    wf = cfg.wf
    parts: list[str] = []
    parts.append("# Out-of-sample results\n")
    parts.append(
        f"_Generated by `make backtest` on {date.today().isoformat()} — do not edit by hand._\n"
    )
    parts.append(
        f"**Study.** Assets {', '.join(cfg.assets)}; horizons "
        f"{', '.join(f'{h}d' for h in cfg.horizons)}; period {cfg.start}→"
        f"{cfg.end or 'today'}. Walk-forward: {wf.mode}, train {wf.train_size}d / "
        f"test {wf.test_size}d, embargo {wf.embargo}d. Costs: "
        f"{cfg.costs.cost_per_side * 1e4:.0f} bps per side.\n"
    )
    parts.append("## Headline: does anything beat the random walk?\n")
    parts.append(_headline(table) + "\n")

    parts.append("## Forecast accuracy & market timing\n")
    parts.append(
        "`R²_oos` is out-of-sample R² vs the mean (negative = worse than predicting "
        "the mean). `DM p` tests equal squared-error accuracy vs the random walk; "
        "`PT p` tests sign predictability.\n"
    )
    acc_header = ["model", "RMSE", "R²_oos", "DirAcc", "RankIC", "DM p vs RW", "PT p"]
    for (asset, horizon), grp in table.groupby(["asset", "horizon"]):
        parts.append(f"\n**{asset} · h={horizon}d**\n")
        rows = [
            [
                r["model"],
                _fmt(r["rmse"], ".4f"),
                _fmt(r["r2_oos"], ".4f"),
                _fmt(r["dir_acc"], ".3f"),
                _fmt(r["rank_ic"], ".3f"),
                _fmt(r["dm_p_vs_rw"], ".3f"),
                _fmt(r["pt_p"], ".3f"),
            ]
            for _, r in grp.iterrows()
        ]
        parts.append(_md_table(rows, acc_header))

    parts.append("\n\n## Net-of-cost trading performance\n")
    parts.append(
        "Sign strategy on a non-overlapping h-day schedule, after "
        f"{cfg.costs.cost_per_side * 1e4:.0f} bps/side. `Sharpe` is annualized with a "
        "95% circular-block-bootstrap CI; `PSR`/`DSR` are the probabilistic and "
        "deflated Sharpe ratios (DSR corrects for trying several models).\n"
    )
    pnl_header = ["model", "Sharpe (net)", "95% CI", "MaxDD", "PSR", "DSR", "trades"]
    for (asset, horizon), grp in table.groupby(["asset", "horizon"]):
        parts.append(f"\n**{asset} · h={horizon}d**\n")
        rows = [
            [
                r["model"],
                _fmt(r["sharpe_net"], ".2f"),
                f"[{_fmt(r['sharpe_lo'], '.2f')}, {_fmt(r['sharpe_hi'], '.2f')}]",
                _fmt(r["max_dd"], ".2%"),
                _fmt(r["psr"], ".2f"),
                _fmt(r["dsr"], ".2f"),
                str(int(r["trades"])),
            ]
            for _, r in grp.iterrows()
        ]
        parts.append(_md_table(rows, pnl_header))

    if figures:
        parts.append("\n\n## Figures\n")
        for fig in figures:
            parts.append(f"![{Path(fig).stem}]({fig})\n")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(parts) + "\n")
